Modify Database type from json text to PostgreSQL
st1t/bootcamp-memo pull request #3
Opened 2020-11-28 11:01 UTC by st1t

Databaseの種類をjsonからPostgreSQLを使うように変更。

- https://bootcamp.fjord.jp/practices/179

2020-12-03 12:52 UTC, u1tnk requested changes
大きくは 「memo_id無しでidだけで良いのでは？」というところです。
他にもいくつか指摘しているのでご確認お願いします。

2020-12-03 12:52 UTC, u1tnk commented on app.rb
> +  memo = Memo.new(id: SecureRandom.uuid, title: params[:title], contents: params[:body])
特に事情無ければ idはDB側で採番されるので新規のときはIDを指定する必要は無いと思います。DBの方もserial型にしてますしね。
というかidは serial型ですけど、 uuid保存できました？

2020-12-03 12:52 UTC, u1tnk commented on docker-compose.yml
> +version: '3'
👍

2020-12-03 12:52 UTC, u1tnk commented on memo.rb
> +    conn = PG.connect(host: DB_HOST, dbname: DB_NAME, user: DB_USER, password: DB_PASSWORD)
ここだけ pg_connectメソッドを使ってないのはクラスメソッドだからだと思いますが、共有できた方が良いですね。

2020-12-03 12:52 UTC, u1tnk commented on memo.rb
> +    conn.exec("DELETE FROM memos WHERE memo_id = '#{@id}'")
prepared statementを使ってないので、@idに "1 or 1 = 1 "とか入れられてしまうと全部消えてしまいます。
sqlインジェクションという脆弱性となりますので、対策しましょう。
他のSQLも同様です。

2020-12-03 12:52 UTC, u1tnk commented on memo.rb
> +    PG.connect(host: DB_HOST, dbname: DB_NAME, user: DB_USER, password: DB_PASSWORD)
このメソッドを呼ぶ度に新たに接続を作っています。
DB接続は一般に遅い処理なので、接続を保持して使い回せるようにしましょう。

2021-01-17 15:25 UTC, st1t commented on app.rb
> +  memo = Memo.new(id: SecureRandom.uuid, title: params[:title], contents: params[:body])
> というかidは serial型ですけど、 uuid保存できました？

言語化するのが難しいのですが、実態はDBのauto incrementのidじゃなくて、別途`memo_id`というカラムを変に持たせていて、そっちの変更扱いになってました。。。
なぜ`memo_id`をもたせてたのか失念してしまったのですが、いずれにしても不要な値であることに間違いはなさそうなので消しました🙏

2021-01-17 15:26 UTC, st1t commented on memo.rb
> +    conn = PG.connect(host: DB_HOST, dbname: DB_NAME, user: DB_USER, password: DB_PASSWORD)
initializeでインスタンス変数としてコネクションを持たせて、共有するように変更しました。

2021-01-17 15:28 UTC, st1t commented on memo.rb
> +    conn.exec("DELETE FROM memos WHERE memo_id = '#{@id}'")
以下の公式サイトを見直したら`exec_params`メソッドでSQLインジェクション対策になるように見受けられたので変更しました。
https://deveiate.org/code/pg/PG/Connection.html#method-i-exec_params

2021-01-17 15:29 UTC, st1t commented on memo.rb
> +    conn = PG.connect(host: DB_HOST, dbname: DB_NAME, user: DB_USER, password: DB_PASSWORD)
クラスメソッドをやめて、app.rb側で呼ぶときに一度オブジェクトを生成してから呼び出すように変更しました。

2021-01-17 15:31 UTC, st1t commented on memo.rb
> +    PG.connect(host: DB_HOST, dbname: DB_NAME, user: DB_USER, password: DB_PASSWORD)
initializeでインスタンス変数としてコネクションを持たせて、共有するように変更しました。

2021-01-18 01:15 UTC, u1tnk commented on memo.rb
> +    @conn.exec_params("DELETE FROM memos WHERE id = '#{@id}'")
https://deveiate.org/code/pg/PG/Connection.html#method-i-exec_params
で sqlインジェクション対策になるのでは？との事ですが、

` exec_params(sql, params [, result_format [, type_map ]] ) → nil`

sqlインジェクション対策とするには、sqlとparamsを分割して書く必要があります。
使っている記事を見つけたので参考にしてください。 https://qiita.com/ibarakishiminn/items/96c5b13a687ee8ca98f2

結局全部文字列して渡すとインジェクションを防ぐのは難しいので、placeholder($1とか)と値を別に渡す必要があります。

2021-01-18 15:28 UTC, st1t commented on memo.rb
> +    @conn.exec_params("DELETE FROM memos WHERE id = '#{@id}'")
なるほど、単に置き換えるのではなく分割する必要があったのですね💦
記事も拝見しました、ありがとうございます！
以下の通り修正してみたのでご確認お願いいたします🙏
https://github.com/st1t/bootcamp-memo/compare/449ce4c1a9a40d6fdc485601ffc0232869d3ca49...96c6fed34be9d3dd41f7a19281eabd5111afa815?expand=1

2021-01-19 01:28 UTC, u1tnk commented on memo.rb
> +    @conn.exec_params("DELETE FROM memos WHERE id = '#{@id}'")
@st1t 
問題無いです 🙆‍♀️

2021-01-19 01:28 UTC, u1tnk approved these changes

2021-01-19 14:22 UTC, merged